<?php

declare(strict_types=1);

namespace App\CLI\Command\Dev;

use App\CLI\Commands;
use EMS\CommonBundle\Common\Command\AbstractCommand;
use EMS\Helpers\File\File;
use EMS\Helpers\File\Folder;
use EMS\Helpers\File\Path;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(
    name: Commands::FAKE_PROJECT_BUILD,
    description: 'Generate a lightweight Symfony project for IDE autocompletion from elasticms-admin versions.',
)]
final class FakeProjectBuilder extends AbstractCommand
{
    /**
     * @var array<string>
     */
    private const array REQUIRED_PACKAGES = [
        'php',
        'doctrine/doctrine-bundle',
        'elasticms/admin-ui-bundle',
        'elasticms/core-bundle',
        'symfony/framework-bundle',
        'symfony/security-bundle',
        'symfony/twig-bundle',
    ];
    private string $destination;
    private bool $force;

    protected function configure(): void
    {
        parent::configure();

        $this
            ->addArgument('destination', InputArgument::REQUIRED, 'Destination directory of the generated fake Symfony project.')
            ->addOption('force', null, InputOption::VALUE_NONE, 'Overwrite files generated by this command if they already exist.');
    }

    #[\Override]
    protected function initialize(InputInterface $input, OutputInterface $output): void
    {
        parent::initialize($input, $output);
        $this->destination = $this->getArgumentString('destination');
        $this->force = $this->getOptionBool('force');
    }

    #[\Override]
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $application = $this->getApplication();
        if ($application instanceof Application) {
            $projectDir = $application->getKernel()->getProjectDir();
        } else {
            $projectDir = \dirname(__DIR__, 2);
        }
        $destination = $this->resolveDestination($this->destination, $projectDir);

        try {
            $composer = $this->loadComposer(\sprintf('%s/composer.json', $projectDir));
            $this->assertDestination($destination);
            $writtenFiles = $this->writeFakeProject($destination, $composer);
        } catch (\Throwable $throwable) {
            $this->io->error($throwable->getMessage());

            return self::EXECUTE_ERROR;
        }

        $this->io->success(\sprintf('Fake Symfony project generated in %s', $destination));
        $this->io->listing([
            'Run `composer install` in the generated directory.',
            'If you need skeleton route autocompletion, provide a sibling `skeleton/routes.yaml` next to the generated project.',
            \sprintf('%d file(s) written.', $writtenFiles),
        ]);

        return self::EXECUTE_SUCCESS;
    }

    /**
     * @param array<string, mixed> $composer
     */
    private function writeFakeProject(string $destination, array $composer): int
    {
        $count = 0;
        foreach ($this->files($composer) as $relativePath => $file) {
            $target = $destination.'/'.$relativePath;
            $this->writeFile($target, $file['contents']);

            if ($file['executable']) {
                @\chmod($target, 0o755);
            }

            ++$count;
        }

        return $count;
    }

    private function assertDestination(string $destination): void
    {
        if (\is_dir($destination)) {
            if (!$this->force && !Folder::isEmpty($destination)) {
                throw new \RuntimeException(\sprintf('Destination directory "%s" already exists and is not empty. Use --force to overwrite generated files.', $destination));
            }

            return;
        }

        if (\file_exists($destination)) {
            throw new \RuntimeException(\sprintf('Destination "%s" exists and is not a directory.', $destination));
        }

        if (!@\mkdir($destination, 0o777, true) && !\is_dir($destination)) {
            throw new \RuntimeException(\sprintf('Unable to create destination directory "%s".', $destination));
        }
    }

    /**
     * @param  array<string, mixed>                                     $composer
     * @return array<string, array{contents: string, executable: bool}>
     */
    private function files(array $composer): array
    {
        return [
            'bin/console' => ['contents' => $this->binConsole(), 'executable' => true],
            'composer.json' => ['contents' => $this->generatedComposerJson($composer), 'executable' => false],
            'config/bundles.php' => ['contents' => $this->bundlesPhp(), 'executable' => false],
            'config/packages/doctrine.yaml' => ['contents' => $this->doctrineYaml(), 'executable' => false],
            'config/packages/ems_client_helper.yaml' => ['contents' => $this->emsClientHelperYaml(), 'executable' => false],
            'config/packages/ems_common.yaml' => ['contents' => $this->emsCommonYaml(), 'executable' => false],
            'config/packages/ems_core.yaml' => ['contents' => $this->emsCoreYaml(), 'executable' => false],
            'config/packages/framework.yaml' => ['contents' => $this->frameworkYaml(), 'executable' => false],
            'config/packages/mercure.yaml' => ['contents' => $this->mercureYaml(), 'executable' => false],
            'config/packages/monolog.yaml' => ['contents' => $this->monologYaml(), 'executable' => false],
            'config/packages/security.yaml' => ['contents' => $this->securityYaml(), 'executable' => false],
            'config/packages/twig.yaml' => ['contents' => $this->twigYaml(), 'executable' => false],
            'config/services.yaml' => ['contents' => $this->servicesYaml(), 'executable' => false],
            'src/Kernel.php' => ['contents' => $this->kernelPhp(), 'executable' => false],
            'tools/generate-phpstorm-skeleton-controller.php' => ['contents' => $this->generatePhpStormSkeletonControllerPhp(), 'executable' => false],
            'tools/generate-phpstorm-twig-extension.php' => ['contents' => $this->generatePhpStormTwigExtensionPhp(), 'executable' => false],
        ];
    }

    private function writeFile(string $path, string $contents): void
    {
        if (\is_file($path) && !$this->force) {
            throw new \RuntimeException(\sprintf('File "%s" already exists. Use --force to overwrite generated files.', $path));
        }

        File::putContents(Folder::createFileDirectories($path), $contents);
    }

    private function resolveDestination(string $destination, string $projectDir): string
    {
        if (Path::isAbsolutePath($destination)) {
            return \rtrim($destination, '/');
        }

        $baseDir = \getcwd() ?: $projectDir;

        return \rtrim($baseDir.'/'.$destination, '/');
    }

    /**
     * @return array<string, mixed>
     */
    private function loadComposer(string $path): array
    {
        if (!\is_file($path)) {
            throw new \RuntimeException(\sprintf('composer.json not found at "%s".', $path));
        }

        try {
            /** @var array<string, mixed> $composer */
            $composer = \json_decode((string) \file_get_contents($path), true, flags: \JSON_THROW_ON_ERROR);
        } catch (\JsonException $jsonException) {
            throw new \RuntimeException(\sprintf('Unable to decode "%s": %s', $path, $jsonException->getMessage()), $jsonException->getCode(), previous: $jsonException);
        }

        return $composer;
    }

    /**
     * @param array<string, mixed> $composer
     */
    private function generatedComposerJson(array $composer): string
    {
        $generated = [
            'name' => 'elasticms/fake-ide-project',
            'description' => 'Generated lightweight Symfony project for ElasticMS IDE autocompletion',
            'type' => 'project',
            'minimum-stability' => $composer['minimum-stability'] ?? 'dev',
            'prefer-stable' => $composer['prefer-stable'] ?? true,
            'require' => $this->generatedRequire($composer),
            'autoload' => [
                'psr-4' => [
                    'App\\' => 'src/',
                ],
            ],
            'scripts' => [
                'post-install-cmd' => [
                    '@php tools/generate-phpstorm-twig-extension.php',
                    '@php tools/generate-phpstorm-skeleton-controller.php',
                ],
                'post-update-cmd' => [
                    '@php tools/generate-phpstorm-twig-extension.php',
                    '@php tools/generate-phpstorm-skeleton-controller.php',
                ],
                'phpstorm-twig' => '@php tools/generate-phpstorm-twig-extension.php',
                'phpstorm-skeleton-routes' => '@php tools/generate-phpstorm-skeleton-controller.php',
            ],
            'config' => [
                'allow-plugins' => [
                    'php-http/discovery' => false,
                ],
            ],
        ];

        $json = \json_encode($generated, \JSON_PRETTY_PRINT | \JSON_UNESCAPED_SLASHES | \JSON_THROW_ON_ERROR);

        return $json."\n";
    }

    /**
     * @param array<string, mixed> $composer
     *
     * @return array<string, string>
     */
    private function generatedRequire(array $composer): array
    {
        /** @var array<string, string> $require */
        $require = [];
        /** @var array<string, string> $sourceRequire */
        $sourceRequire = \is_array($composer['require'] ?? null) ? $composer['require'] : [];

        $elasticmsVersion = $sourceRequire['elasticms/common-bundle'] ?? null;
        if (!$elasticmsVersion) {
            throw new \RuntimeException('The source composer.json file does not specify an "elasticms/common-bundle" version constraint.');
        }
        $symfonyVersion = $sourceRequire['symfony/console'] ?? null;
        if (!$symfonyVersion) {
            throw new \RuntimeException('The source composer.json file does not specify a "symfony/console" version constraint.');
        }

        foreach (self::REQUIRED_PACKAGES as $package) {
            if (isset($sourceRequire[$package])) {
                $require[$package] = $sourceRequire[$package];
            } elseif (\str_starts_with($package, 'elasticms/')) {
                $require[$package] = $elasticmsVersion;
            } elseif (\str_starts_with($package, 'symfony/')) {
                $require[$package] = $symfonyVersion;
            } else {
                throw new \RuntimeException(\sprintf('The source composer.json file does not specify a "%s" version constraint.', $package));
            }
        }

        \ksort($require);

        return $require;
    }

    private function binConsole(): string
    {
        return <<<'PHP'
            #!/usr/bin/env php
            <?php

            use App\Kernel;
            use Symfony\Bundle\FrameworkBundle\Console\Application;

            require dirname(__DIR__).'/vendor/autoload.php';
            require dirname(__DIR__).'/src/Kernel.php';

            $kernel = new Kernel($_SERVER['APP_ENV'] ?? 'dev', (bool) ($_SERVER['APP_DEBUG'] ?? true));
            $application = new Application($kernel);
            $application->run();
            PHP;
    }

    private function kernelPhp(): string
    {
        return <<<'PHP'
            <?php

            declare(strict_types=1);

            namespace App;

            use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
            use Symfony\Component\HttpKernel\Kernel as BaseKernel;

            class Kernel extends BaseKernel
            {
                use MicroKernelTrait;
            }
            PHP;
    }

    private function bundlesPhp(): string
    {
        return <<<'PHP'
            <?php

            return [
                Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
                Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
                Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
                Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
                Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
                Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
                Symfony\UX\TwigComponent\TwigComponentBundle::class => ['all' => true],
                Symfony\Bundle\MercureBundle\MercureBundle::class => ['all' => true],

                EMS\ClientHelperBundle\EMSClientHelperBundle::class => ['all' => true],
                EMS\CommonBundle\EMSCommonBundle::class => ['all' => true],
                EMS\CoreBundle\EMSCoreBundle::class => ['all' => true],
            ];
            PHP;
    }

    private function servicesYaml(): string
    {
        return <<<'YAML'
            services:
                _defaults:
                    autowire: true
                    autoconfigure: true

                App\:
                    resource: '../src/'
            YAML;
    }

    private function doctrineYaml(): string
    {
        return <<<'YAML'
            doctrine:
                dbal:
                    url: 'sqlite:///%kernel.cache_dir%/ide-elasticms.sqlite'
                orm:
                    mappings: []
            YAML;
    }

    private function emsClientHelperYaml(): string
    {
        return <<<'YAML'
            ems_client_helper:
                request_environments: []
                locales: ['fr']
                bind_locale: false
                etag_hash_algo: 'sha1'
                elasticms:
                    default:
                        hosts: ['http://localhost:9200']
            YAML;
    }

    private function emsCommonYaml(): string
    {
        return <<<'YAML'
            ems_common:
                metric:
                    enabled: true
                    host: '127.0.0.1'
                    port: 0
            YAML;
    }

    private function emsCoreYaml(): string
    {
        return <<<'YAML'
            ems_core:
                # IDE-only project: avoid warming the local Tika jar, which is not shipped
                # with this lightweight skeleton.
                tika_server: 'http://127.0.0.1:9998'
            YAML;
    }

    private function frameworkYaml(): string
    {
        return <<<'YAML'
            framework:
                secret: 'dev'
                form: true
                http_method_override: false
                csrf_protection: true
                validation: true
                translator:
                    default_path: '%kernel.project_dir%/translations'
                session:
                    storage_factory_id: session.storage.factory.mock_file
                mailer:
                    dsn: 'null://null'
            YAML;
    }

    private function mercureYaml(): string
    {
        return <<<'YAML'
            mercure:
                hubs:
                    default:
                        url: 'http://localhost/.well-known/mercure'
                        jwt:
                            value: 'fake'
            YAML;
    }

    private function monologYaml(): string
    {
        return <<<'YAML'
            monolog:
                handlers:
                    main:
                        type: stream
                        path: '%kernel.logs_dir%/%kernel.environment%.log'
                        level: debug
            YAML;
    }

    private function securityYaml(): string
    {
        return <<<'YAML'
            security:
                password_hashers:
                    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto
                providers:
                    in_memory:
                        memory: null
                firewalls:
                    dev:
                        pattern: ^/(_(profiler|wdt)|css|images|js)/
                        security: false
                    main:
                        lazy: true
                        provider: in_memory
            YAML;
    }

    private function twigYaml(): string
    {
        return <<<'YAML'
            twig:
                default_path: '%kernel.project_dir%/../skeleton'
            YAML;
    }

    private function generatePhpStormTwigExtensionPhp(): string
    {
        return <<<'PHP'
            <?php

            declare(strict_types=1);

            use Twig\Attribute\AsTwigFilter;
            use Twig\Attribute\AsTwigFunction;
            use Twig\Attribute\AsTwigTest;

            require __DIR__.'/../vendor/autoload.php';

            $projectDir = \dirname(__DIR__);
            $packages = [
                'elasticms/client-helper-bundle',
                'elasticms/common-bundle',
                'elasticms/core-bundle',
                'elasticms/form-bundle',
                'elasticms/submission-bundle',
            ];

            $callables = [
                'filters' => [],
                'functions' => [],
                'tests' => [],
            ];

            foreach ($packages as $package) {
                $composerFile = $projectDir.'/vendor/'.$package.'/composer.json';
                if (!\is_file($composerFile)) {
                    continue;
                }

                $composer = \json_decode((string) \file_get_contents($composerFile), true, flags: JSON_THROW_ON_ERROR);
                foreach (($composer['autoload']['psr-4'] ?? []) as $namespace => $paths) {
                    foreach ((array) $paths as $path) {
                        $sourceDir = $projectDir.'/vendor/'.$package.'/'.\rtrim((string) $path, '/').'/Twig';
                        if (!\is_dir($sourceDir)) {
                            continue;
                        }

                        foreach (phpFiles($sourceDir) as $file) {
                            $class = className($namespace, $sourceDir, $file);
                            if (null === $class || !\class_exists($class)) {
                                continue;
                            }

                            scanClass($class, $callables);
                        }
                    }
                }
            }

            foreach ($callables as &$items) {
                \ksort($items);
            }
            unset($items);

            $target = $projectDir.'/src/PhpStorm/GeneratedElasticmsTwigAttributeExtension.php';
            \is_dir(\dirname($target)) || \mkdir(\dirname($target), 0777, true);
            \file_put_contents($target, renderExtension($callables));

            echo \sprintf("Generated %s\n", $target);

            /**
             * @return iterable<string>
             */
            function phpFiles(string $directory): iterable
            {
                $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($directory));

                foreach ($iterator as $file) {
                    if ($file instanceof SplFileInfo && $file->isFile() && 'php' === $file->getExtension()) {
                        yield $file->getPathname();
                    }
                }
            }

            function className(string $namespace, string $sourceDir, string $file): ?string
            {
                $relative = \substr($file, \strlen($sourceDir) + 1);
                if (false === $relative || !\str_ends_with($relative, '.php')) {
                    return null;
                }

                return \rtrim($namespace, '\\').'\\Twig\\'.\str_replace('/', '\\', \substr($relative, 0, -4));
            }

            /**
             * @param array{filters: array<string, array{class: class-string, method: string, options: array<string, mixed>}>, functions: array<string, array{class: class-string, method: string, options: array<string, mixed>}>, tests: array<string, array{class: class-string, method: string, options: array<string, mixed>}>} $callables
             */
            function scanClass(string $class, array &$callables): void
            {
                $reflection = new ReflectionClass($class);
                foreach ($reflection->getMethods() as $method) {
                    foreach ($method->getAttributes(AsTwigFilter::class) as $attribute) {
                        $instance = $attribute->newInstance();
                        $callables['filters'][$instance->name] = [
                            'class' => $class,
                            'method' => $method->getName(),
                            'options' => callableOptions($instance, $method),
                        ];
                    }

                    foreach ($method->getAttributes(AsTwigFunction::class) as $attribute) {
                        $instance = $attribute->newInstance();
                        $callables['functions'][$instance->name] = [
                            'class' => $class,
                            'method' => $method->getName(),
                            'options' => callableOptions($instance, $method),
                        ];
                    }

                    foreach ($method->getAttributes(AsTwigTest::class) as $attribute) {
                        $instance = $attribute->newInstance();
                        $callables['tests'][$instance->name] = [
                            'class' => $class,
                            'method' => $method->getName(),
                            'options' => callableOptions($instance, $method),
                        ];
                    }
                }
            }

            /**
             * @return array<string, mixed>
             */
            function callableOptions(object $attribute, ReflectionMethod $method): array
            {
                $options = [
                    'needs_context' => $attribute->needsContext ?? false,
                    'needs_environment' => $attribute->needsEnvironment ?? needsEnvironment($method),
                    'needs_charset' => $attribute->needsCharset ?? false,
                    'is_variadic' => $method->isVariadic(),
                    'is_safe' => $attribute->isSafe ?? [],
                ];

                if (\property_exists($attribute, 'isSafeCallback')) {
                    $options['is_safe_callback'] = $attribute->isSafeCallback;
                }
                if (\property_exists($attribute, 'preEscape')) {
                    $options['pre_escape'] = $attribute->preEscape;
                }
                if (\property_exists($attribute, 'preservesSafety')) {
                    $options['preserves_safety'] = $attribute->preservesSafety;
                }
                if (\property_exists($attribute, 'deprecationInfo')) {
                    $options['deprecation_info'] = $attribute->deprecationInfo;
                }

                return \array_filter($options, static fn (mixed $value): bool => null !== $value && [] !== $value && false !== $value);
            }

            function needsEnvironment(ReflectionMethod $method): bool
            {
                $parameters = $method->getParameters();
                if ([] === $parameters) {
                    return false;
                }

                $type = $parameters[0]->getType();

                return $type instanceof ReflectionNamedType
                    && Twig\Environment::class === $type->getName()
                    && !$parameters[0]->isVariadic();
            }

            /**
             * @param array{filters: array<string, array{class: class-string, method: string, options: array<string, mixed>}>, functions: array<string, array{class: class-string, method: string, options: array<string, mixed>}>, tests: array<string, array{class: class-string, method: string, options: array<string, mixed>}>} $callables
             */
            function renderExtension(array $callables): string
            {
                $filters = renderCallables($callables['filters'], 'TwigFilter');
                $functions = renderCallables($callables['functions'], 'TwigFunction');
                $tests = renderCallables($callables['tests'], 'TwigTest');

                return <<<TWIG_EXTENSION
            <?php

            declare(strict_types=1);

            namespace App\\PhpStorm;

            use Twig\\Extension\\AbstractExtension;
            use Twig\\TwigFilter;
            use Twig\\TwigFunction;
            use Twig\\TwigTest;

            /**
             * Generated by tools/generate-phpstorm-twig-extension.php.
             */
            final class GeneratedElasticmsTwigAttributeExtension extends AbstractExtension
            {
                public function getFilters(): array
                {
                    return [
            $filters
                    ];
                }

                public function getFunctions(): array
                {
                    return [
            $functions
                    ];
                }

                public function getTests(): array
                {
                    return [
            $tests
                    ];
                }
            }

            TWIG_EXTENSION;
            }

            /**
             * @param array<string, array{class: class-string, method: string, options: array<string, mixed>}> $callables
             */
            function renderCallables(array $callables, string $twigClass): string
            {
                $lines = [];
                foreach ($callables as $name => $callable) {
                    $arguments = [
                        \var_export($name, true),
                        '[\\'.$callable['class'].'::class, '.\var_export($callable['method'], true).']',
                    ];
                    if ([] !== $callable['options']) {
                        $arguments[] = shortArray($callable['options']);
                    }

                    $lines[] = '            new '.$twigClass.'('.\implode(', ', $arguments).'),';
                }

                return \implode("\n", $lines);
            }

            /**
             * @param array<string, mixed> $array
             */
            function shortArray(array $array): string
            {
                $items = [];
                foreach ($array as $key => $value) {
                    $items[] = \var_export($key, true).' => '.(\is_array($value) ? shortArray($value) : \var_export($value, true));
                }

                return '['.\implode(', ', $items).']';
            }
            PHP;
    }

    private function generatePhpStormSkeletonControllerPhp(): string
    {
        return <<<'PHP'
            <?php

            declare(strict_types=1);

            use Symfony\Component\Config\FileLocator;
            use Symfony\Component\Config\Loader\LoaderResolver;
            use Symfony\Component\Routing\Loader\PhpFileLoader;
            use Symfony\Component\Routing\Loader\XmlFileLoader;
            use Symfony\Component\Routing\Route;
            use Symfony\Component\Yaml\Yaml;

            require __DIR__.'/../vendor/autoload.php';

            final class BundleAwareFileLocator extends FileLocator
            {
                /**
                 * @param array<string, string> $bundlePaths
                 */
                public function __construct(private readonly array $bundlePaths)
                {
                    parent::__construct();
                }

                public function locate(string $name, ?string $currentPath = null, bool $first = true): string|array
                {
                    if (\str_starts_with($name, '@')) {
                        [$bundleName, $resource] = \explode('/', \substr($name, 1), 2);
                        if (!isset($this->bundlePaths[$bundleName])) {
                            throw new RuntimeException(\sprintf('Unknown bundle resource: %s', $name));
                        }

                        return parent::locate($this->bundlePaths[$bundleName].'/'.$resource, $currentPath, $first);
                    }

                    return parent::locate($name, $currentPath, $first);
                }
            }

            $skeletonDir = __DIR__.'/../../skeleton';
            $routesFile = $skeletonDir.'/routes.yaml';
            $target = __DIR__.'/../src/PhpStorm/GeneratedSkeletonController.php';

            if (!\is_file($routesFile)) {
                throw new RuntimeException(\sprintf('Routes file not found: %s', $routesFile));
            }

            /** @var array<string, array{config?: array<string, mixed>}> $routes */
            \is_array($skeletonRoutes = Yaml::parseFile($routesFile)) || throw new RuntimeException(\sprintf('Invalid routes structure in %s', $routesFile));
            $routes = $skeletonRoutes;
            $routes = \array_replace($routes, bundleRoutes());
            \ksort($routes);

            \is_dir(\dirname($target)) || \mkdir(\dirname($target), 0777, true);
            \file_put_contents($target, renderController($routes));

            echo \sprintf("Generated %s\n", $target);

            /**
             * @return array<string, array{config: array<string, mixed>}>
             */
            function bundleRoutes(): array
            {
                $bundlePaths = bundlePaths();
                $resources = [
                    'EMSClientHelperBundle' => [
                        'config/routing/core_bridge.php',
                        'config/routing/user_api.php',
                    ],
                    'EMSCommonBundle' => [
                        'config/routing/assets.php',
                        'config/routing/file.php',
                        'config/routing/probe.php',
                    ],
                    'EMSCoreBundle' => [
                        'config/routing/all.php',
                    ],
                    'EMSFormBundle' => [
                        'config/routing/debug.php',
                        'config/routing/form.php',
                    ],
                    'EMSSubmissionBundle' => [],
                ];

                $locator = new BundleAwareFileLocator($bundlePaths);
                $phpLoader = new PhpFileLoader($locator);
                $xmlLoader = new XmlFileLoader($locator);
                $resolver = new LoaderResolver([$phpLoader, $xmlLoader]);
                $phpLoader->setResolver($resolver);
                $xmlLoader->setResolver($resolver);

                $routes = [];
                foreach ($resources as $bundleName => $files) {
                    foreach ($files as $file) {
                        if (!isset($bundlePaths[$bundleName])) {
                            continue;
                        }

                        $collection = $phpLoader->load('@'.$bundleName.'/'.$file);
                        foreach ($collection->all() as $name => $route) {
                            $routes[$name] = [
                                'config' => routeConfig($route),
                            ];
                        }
                    }
                }

                return $routes;
            }

            /**
             * @return array<string, string>
             */
            function bundlePaths(): array
            {
                $classes = [
                    EMS\ClientHelperBundle\EMSClientHelperBundle::class,
                    EMS\CommonBundle\EMSCommonBundle::class,
                    EMS\CoreBundle\EMSCoreBundle::class,
                    EMS\FormBundle\EMSFormBundle::class,
                    EMS\SubmissionBundle\EMSSubmissionBundle::class,
                ];

                $paths = [];
                foreach ($classes as $class) {
                    if (!\class_exists($class)) {
                        continue;
                    }

                    $reflection = new ReflectionClass($class);
                    $paths[$reflection->getShortName()] = \dirname($reflection->getFileName(), 2);
                }

                return $paths;
            }

            /**
             * @return array<string, mixed>
             */
            function routeConfig(Route $route): array
            {
                $config = [
                    'path' => $route->getPath(),
                ];

                if ([] !== $defaults = \array_diff_key($route->getDefaults(), ['_controller' => true])) {
                    $config['defaults'] = $defaults;
                }
                if ([] !== $requirements = $route->getRequirements()) {
                    $config['requirements'] = $requirements;
                }
                if ('' !== $host = $route->getHost()) {
                    $config['host'] = $host;
                }
                if ([] !== $schemes = $route->getSchemes()) {
                    $config['schemes'] = $schemes;
                }
                if ([] !== $methods = $route->getMethods()) {
                    $config['methods'] = $methods;
                }
                if (null !== $condition = $route->getCondition()) {
                    $config['condition'] = $condition;
                }
                if (null !== $format = $route->getDefault('_format')) {
                    $config['format'] = $format;
                }
                if ($route->hasOption('utf8')) {
                    $config['utf8'] = $route->getOption('utf8');
                }
                if ($route->hasOption('compiler_class')) {
                    unset($config['compiler_class']);
                }

                return $config;
            }

            /**
             * @param array<string, array{config?: array<string, mixed>}> $routes
             */
            function renderController(array $routes): string
            {
                $methods = [];
                $usedMethodNames = [];

                foreach ($routes as $name => $route) {
                    $config = $route['config'] ?? [];
                    if (!\is_array($config) || !isset($config['path'])) {
                        continue;
                    }

                    $methods[] = renderMethod($name, $config, uniqueMethodName($name, $usedMethodNames));
                }

                $methodsBlock = \implode("\n\n", $methods);

                return <<<SKELETON_CONTROLLER
            <?php

            declare(strict_types=1);

            namespace App\\PhpStorm;

            use Symfony\\Component\\HttpFoundation\\Response;
            use Symfony\\Component\\Routing\\Attribute\\Route;

            /**
             * Generated by tools/generate-phpstorm-skeleton-controller.php from /workspace/skeleton/routes.yaml.
             */
            final class GeneratedSkeletonController
            {
            $methodsBlock
            }

            SKELETON_CONTROLLER;
            }

            /**
             * @param array<string, mixed> $config
             */
            function renderMethod(string $name, array $config, string $methodName): string
            {
                $arguments = ["name: ".exportValue($name)];

                foreach (['path', 'defaults', 'requirements', 'host', 'schemes', 'methods', 'condition', 'priority', 'env', 'format', 'utf8', 'stateless'] as $key) {
                    if (\array_key_exists($key, $config)) {
                        $arguments[] = $key.': '.exportValue($config[$key]);
                    }
                }

                $parameters = [];
                foreach (methodParameters($config) as $parameter) {
                    $parameters[] = renderParameter($parameter);
                }

                $signature = [] === $parameters ? '' : \implode(', ', $parameters);
                $attribute = '#[Route('.\implode(', ', $arguments).')]';

                return <<<ROUTE_METHOD
                $attribute
                public function $methodName($signature): Response
                {
                    return new Response();
                }
            ROUTE_METHOD;
            }

            function methodName(string $routeName): string
            {
                $name = \preg_replace('/[^a-zA-Z0-9]+/', ' ', $routeName) ?? $routeName;
                $name = \str_replace(' ', '', \ucwords(\trim($name)));
                $name = '' === $name ? 'generatedRoute' : \lcfirst($name);

                if (\is_numeric($name[0])) {
                    $name = 'route'.$name;
                }

                return $name;
            }

            /**
             * @param array<string, true> $usedMethodNames
             */
            function uniqueMethodName(string $routeName, array &$usedMethodNames): string
            {
                $baseName = methodName($routeName);
                $name = $baseName;
                $suffix = 2;

                while (isset($usedMethodNames[$name])) {
                    $name = $baseName.$suffix;
                    ++$suffix;
                }

                $usedMethodNames[$name] = true;

                return $name;
            }

            /**
             * @param array<string, mixed> $config
             *
             * @return array<int, array{name: string, default: mixed, hasDefault: bool}>
             */
            function methodParameters(array $config): array
            {
                $names = [];
                foreach ((array) ($config['path'] ?? []) as $path) {
                    if (!\is_string($path)) {
                        continue;
                    }

                    if (\preg_match_all('/\{([A-Za-z_][A-Za-z0-9_]*)\}/', $path, $matches)) {
                        foreach ($matches[1] as $match) {
                            $names[$match] = true;
                        }
                    }
                }

                $defaults = \is_array($config['defaults'] ?? null) ? $config['defaults'] : [];
                $parameters = [];

                foreach (\array_keys($names) as $name) {
                    $parameters[] = [
                        'name' => $name,
                        'default' => $defaults[$name] ?? null,
                        'hasDefault' => \array_key_exists($name, $defaults),
                    ];
                }

                \usort($parameters, static function (array $left, array $right): int {
                    return ($left['hasDefault'] <=> $right['hasDefault']) ?: 0;
                });

                return $parameters;
            }

            /**
             * @param array{name: string, default: mixed, hasDefault: bool} $parameter
             */
            function renderParameter(array $parameter): string
            {
                $name = '$'.$parameter['name'];
                if (!$parameter['hasDefault']) {
                    return 'string '.$name;
                }

                $default = $parameter['default'];
                if (\is_int($default)) {
                    return 'int '.$name.' = '.exportValue($default);
                }
                if (\is_bool($default)) {
                    return 'bool '.$name.' = '.exportValue($default);
                }
                if (null === $default) {
                    return '?string '.$name.' = null';
                }

                return 'string '.$name.' = '.exportValue((string) $default);
            }

            function exportValue(mixed $value): string
            {
                if (\is_array($value)) {
                    return shortArray($value);
                }

                return \var_export($value, true);
            }

            /**
             * @param array<mixed> $array
             */
            function shortArray(array $array): string
            {
                $items = [];
                foreach ($array as $key => $value) {
                    $renderedValue = \is_array($value) ? shortArray($value) : \var_export($value, true);

                    if (\is_int($key)) {
                        $items[] = $renderedValue;
                        continue;
                    }

                    $items[] = \var_export($key, true).' => '.$renderedValue;
                }

                return '['.\implode(', ', $items).']';
            }
            PHP;
    }
}
