documentation: ["*.md"]
elasticms-admin: ["/elasticms-admin"]
elasticms-web: ["/elasticms-web"]
elasticms-cli: ["/elasticms-cli"]
demo: ["/demo"]
client-helper-bundle: ["/EMS/client-helper-bundle"]
common-bundle: ["/EMS/common-bundle"]
core-bundle: ["/EMS/core-bundle"]
form-bundle: ["/EMS/form-bundle"]
submission-bundle: ["/EMS/submission-bundle"]