  version: '3.5'

  services:

    keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        KC_DB: postgres
        KC_DB_VENDOR: POSTGRES
        KC_DB_DATABASE: keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KC_DB_URL_HOST: db
        KC_DB_SCHEMA: public
        KC_DB_PORT: 5432
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: changeme
        KEYCLOAK_LOGLEVEL: ALL
      volumes:
        - ./data:/data
      ports:
        - "8083:8080"
      command: [ 'start-dev' ]
      depends_on:
        - db
      restart: always

    db:
      image: postgres:13
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      volumes:
        - postgres:/var/lib/postgresql/data

  volumes:
    postgres:
