files:
    resource: '@EMSCommonBundle/config/routing/file.php'

assets:
    resource: '@EMSCommonBundle/config/routing/assets.php'

probe:
    resource: '@EMSCommonBundle/config/routing/probe.php'

forms:
    resource: '@EMSFormBundle/config/routing/form.php'

user_api:
    resource: '@EMSClientHelperBundle/config/routing/user_api.php'
    prefix: /user_api

ems_common:
    resource: 'ems_common.route.loader::load'
    type: service

emsch_routes:
    resource: 'emsch.routing.route_loader'
    type: service
