parameters:
    locale: '%env(DEFAULT_LOCAL)%'
    env(REDIS_HOST): ''
    env(REDIS_PORT): 6379

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EMS\ClientHelperBundle\Helper\Elasticsearch\ClientRequest: '@emsch.client_request.website'

    #Redis configuration
    Redis:
        # you can also use \RedisArray, \RedisCluster or \Predis\Client classes
        class: Redis
        calls:
            - connect:
                  - '%env(REDIS_HOST)%'
                  - '%env(int:REDIS_PORT)%'
    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'