{
 "title": "EMS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PHP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "php_info", "legendFormat": "{{ version }}" }
   ]
  },
  {
   "title": "Core",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ems_info", "legendFormat": "{{ core }}" }
   ]
  },
  {
   "title": "Symfony",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ems_info", "legendFormat": "{{ symfony }}" }
   ]
  },
  {
   "title": "ElasticMS Jobs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "targets": [
    { "expr": "emsco_job_count_jobs", "legendFormat": "__auto" },
    { "expr": "emsco_job_count_jobs_started", "legendFormat": "__auto" },
    { "expr": "emsco_job_count_jobs_done", "legendFormat": "__auto" }
   ]
  }
 ]
}