version: '3.5'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: ems-mono-keycloak
    environment:
      KC_DB: postgres
      KC_DB_VENDOR: POSTGRES
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL_HOST: keycloak_db
      KC_DB_SCHEMA: public
      KC_DB_PORT: 5432
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: changeme
      KEYCLOAK_LOGLEVEL: ALL
    volumes:
      - ./data:/data
    ports:
      - "9081:8080"
    command: [ 'start-dev' ]
    depends_on:
      - keycloak_db
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)"
      - "traefik.http.routers.keycloak.entrypoints=web"
      - "traefik.http.routers.keycloak.service=keycloak"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"

  keycloak_db:
    image: postgres:13
    container_name: ems-mono-keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:

networks:
  default:
    name: skeleton
