services:
    prometheus:
        profiles: [ "all","grafana" ]
        labels:
            - "elasticMS"
        image: prom/prometheus:latest
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - prometheus_data:/prometheus
        ports:
            - "9090:9090"
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"

    grafana:
        profiles: [ "all","grafana" ]
        image: grafana/grafana-oss:latest
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_INSTALL_PLUGINS=
            - GF_UPDATE_CHECKS_ENABLED=false
        depends_on:
            - prometheus
        volumes:
            - ./grafana/provisioning:/etc/grafana/provisioning:ro
            - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
            - grafana_data:/var/lib/grafana
        ports:
            - "3001:3000"
        restart: unless-stopped
        labels:
            - "elasticMS"
            - "traefik.enable=true"
            - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
            - "traefik.http.routers.grafana.entrypoints=web"
            - "traefik.http.routers.grafana.service=grafana"
            - "traefik.http.services.grafana.loadbalancer.server.port=3000"

volumes:
    prometheus_data:
    grafana_data: