version: "2.4"

services:

  website:
    image: "nginxinc/nginx-s3-gateway"
    environment:
      - AWS_ACCESS_KEY_ID=accesskey
      - AWS_SECRET_ACCESS_KEY=secretkey
      - AWS_SIGS_VERSION=4
      - S3_BUCKET_NAME=website
      - S3_SERVER=minio
      - S3_SERVER_PORT=9000
      - S3_SERVER_PROTO=http
      - S3_REGION=us-east-1
      - S3_STYLE=path
      - ALLOW_DIRECTORY_LIST=false
      - APPEND_SLASH_FOR_POSSIBLE_DIRECTORY=true
      - PROVIDE_INDEX_PAGE=true
      - PROXY_CACHE_VALID_OK=1m
      - PROXY_CACHE_INACTIVE=1m
      - DEBUG=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`website.localhost`)"
      - "traefik.http.routers.website.entrypoints=web"
      - "traefik.http.routers.website.service=website"
      - "traefik.http.services.website.loadbalancer.server.port=80"


networks:
  default:
    name: skeleton
