# This configuration file is autogenerated by the container startup script

map $request_uri $symfony_script_name {
    default "/index.php";
    
    {{- range (datasource "aliases") }}
    ~^{{ . }}/ "{{ . }}/index.php";
    {{- end }}

}
