parameters:
    env(EMSCH_ELASTICSEARCH_CLUSTER):   '["http://localhost:9200"]'
    env(EMS_ELASTICSEARCH_HOSTS):       '%env(string:EMSCH_ELASTICSEARCH_CLUSTER)%'
    env(EMSCH_LOCALES):                 '["fr","nl"]'
    env(EMSCH_BIND_LOCALE):             true
    env(EMSCH_ENVS):                    '{}'

    env(EMSCH_ROUTE_TYPE):              'route'
    env(EMSCH_TRANSLATION_TYPE):        'label'
    env(EMSCH_ASSET_CONFIG_TYPE):       ~
    env(EMSCH_SEARCH_CONFIG):           '{}'
    env(EMSCH_TEMPLATES):               '{"template": {"name": "name","code": "body"}}'

    env(EMSCH_TEMPLATE_ERROR):          '@@EMSCH/template/error{code}.html.twig'
    env(EMSCH_TEMPLATE_EMS_LINK):       '@@EMSCH/template/{type}.ems_link.twig'

    env(EMSCH_BACKEND_URL):             ~
    env(EMSCH_BACKEND_API_KEY):         ~
    env(EMSCH_ASSET_LOCAL_FOLDER):      ~
    env(EMSCH_SEARCH_LIMIT):            '1000'
    env(EMSCH_LOCAL_PATH):              ~

    env(EMSCH_SECURITY_ROUTE_LOGIN):    'emsch_login'

    env(EMSCH_OAUTH2):                      false
    env(EMSCH_OAUTH2_AUTH_SERVER):          ~
    env(EMSCH_OAUTH2_REALM):                ~
    env(EMSCH_OAUTH2_CLIENT_ID):            ~
    env(EMSCH_OAUTH2_CLIENT_SECRET):        ~
    env(EMSCH_OAUTH2_REDIRECT_URI):         ~
    env(EMSCH_OAUTH2_VERSION):              ~
    env(EMSCH_OAUTH2_ENCRYPTION_ALGORITHM): ~
    env(EMSCH_OAUTH2_ENCRYPTION_KEY):       ~

    env(EMSCH_SAML):                    false
    env(EMSCH_SAML_SP_ENTITY_ID):       ~
    env(EMSCH_SAML_SP_PUBLIC_KEY):      ~
    env(EMSCH_SAML_SP_PRIVATE_KEY):     ~
    env(EMSCH_SAML_IDP_ENTITY_ID):      ~
    env(EMSCH_SAML_IDP_PUBLIC_KEY):     ~
    env(EMSCH_SAML_IDP_SSO):            ~
    env(EMSCH_SAML_SECURITY):           '{}'

ems_client_helper:
    api:
        backend:
            url: '%env(string:EMSCH_BACKEND_URL)%'
            key: '%env(string:EMSCH_BACKEND_API_KEY)%'
    locales: '%env(json:EMSCH_LOCALES)%'
    bind_locale: '%env(bool:EMSCH_BIND_LOCALE)%'
    asset_local_folder: '%env(string:EMSCH_ASSET_LOCAL_FOLDER)%'
    request_environments: '%env(json:EMSCH_ENVS)%'
    search_limit: '%env(int:EMSCH_SEARCH_LIMIT)%'
    elasticms:
        website:
            api: {"enable": true, "name": "backend"}
            hosts: '%env(json:EMS_ELASTICSEARCH_HOSTS)%'
            route_type: '%env(string:EMSCH_ROUTE_TYPE)%'
            translation_type: '%env(string:EMSCH_TRANSLATION_TYPE)%'
            asset_config_type: '%env(string:EMSCH_ASSET_CONFIG_TYPE)%'
            templates: '%env(json:EMSCH_TEMPLATES)%'
            search_config: '%env(json:EMSCH_SEARCH_CONFIG)%'
    templates:
        error:    '%env(string:EMSCH_TEMPLATE_ERROR)%'
        ems_link:  '%env(string:EMSCH_TEMPLATE_EMS_LINK)%'
    user_api:
        url: '%env(string:EMSCH_BACKEND_URL)%'
    security:
        route_login: '%env(string:EMSCH_SECURITY_ROUTE_LOGIN)%'
        sso:
            oauth2:
                enabled: '%env(bool:EMSCH_OAUTH2)%'
                auth_server: '%env(string:EMSCH_OAUTH2_AUTH_SERVER)%'
                realm: '%env(string:EMSCH_OAUTH2_REALM)%'
                client_id: '%env(string:EMSCH_OAUTH2_CLIENT_ID)%'
                client_secret: '%env(string:EMSCH_OAUTH2_CLIENT_SECRET)%'
                redirect_uri: '%env(string:EMSCH_OAUTH2_REDIRECT_URI)%'
                version: '%env(string:EMSCH_OAUTH2_VERSION)%'
                encryption_key: '%env(string:EMSCH_OAUTH2_ENCRYPTION_KEY)%'
                encryption_algorithm: '%env(string:EMSCH_OAUTH2_ENCRYPTION_ALGORITHM)%'
            saml:
                enabled: '%env(bool:EMSCH_SAML)%'
                sp_entity_id: '%env(string:EMSCH_SAML_SP_ENTITY_ID)%'
                sp_public_key: '%env(string:EMSCH_SAML_SP_PUBLIC_KEY)%'
                sp_private_key: '%env(string:EMSCH_SAML_SP_PRIVATE_KEY)%'
                idp_entity_id: '%env(string:EMSCH_SAML_IDP_ENTITY_ID)%'
                idp_public_key: '%env(string:EMSCH_SAML_IDP_PUBLIC_KEY)%'
                idp_sso: '%env(string:EMSCH_SAML_IDP_SSO)%'
                security: '%env(json:EMSCH_SAML_SECURITY)%'

when@dev:
    ems_client_helper:
        local:
            path: '%env(string:EMSCH_LOCAL_PATH)%'
