security:
    providers:
        core_api:
            id: emsch.security.core_api.user_provider
        sso:
            id: emsch.security.sso.user_provider
        chain_providers:
            chain:
                providers: [ 'core_api', 'sso' ]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            entry_point: emsch.security.firewall.entry_point
            provider: chain_providers
            custom_authenticators:
                - emsch.security.core_api.authenticator
                - emsch.security.sso.oauth2.authenticator
                - emsch.security.sso.saml.authenticator
            logout:
                path: emsch_logout

    access_control:
        - { path: ^/, roles: PUBLIC_ACCESS }
