#!/usr/bin/env bash
# This script is autogenerated by the container startup script

set -o allexport
source {{ .Env.APP_CONFIG_DIR }}/{{ .Env.ELASTICMS_INSTANCE_NAME }}
set +o allexport

php -d memory_limit=${CLI_PHP_MEMORY_LIMIT:-512M} {{ .Env.APP_SRC_DIR }}/bin/console "$@"
