#!/usr/bin/env bash
# This script is autogenerated by the container startup script

set -o allexport
source {{ .Env.APP_CONFIG_DIR }}/{{ .Env.ELASTICMS_INSTANCE_NAME }}
set +o allexport

php {{ .Env.APP_SRC_DIR }}/bin/console "$@"
