#!/usr/bin/env php
<?php
require __DIR__.'/../vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application('release', '1.0.0');

$application->add((new \EMS\Release\Command\ComposerUpdate()));

$application->add((new \EMS\Release\Command\GitHubBranchesCommand()));
$application->add((new \EMS\Release\Command\GithubReleaseCommand('applications', '4) Release applications admin/web/cli')));
$application->add((new \EMS\Release\Command\GithubReleaseCommand('packages', '1) Release packages')));
$application->add((new \EMS\Release\Command\GithubReleaseCommand('docker', '5) Release docker admin/web/cli')));

$application->add((new \EMS\Release\Command\PackagistInfo()));

$application->run();