#!/usr/bin/env php
<?php
require __DIR__.'/../vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application('release', '1.0.0');

$application->add((new \EMS\Release\Command\PackagesReleaseCommand()));
$application->add((new \EMS\Release\Command\PackagesInfoCommand()));

$application->run();