#!/usr/bin/env php
<?php

require __DIR__.'/../vendor/autoload.php';

use EMS\Release\Command;
use EMS\Release\ReleaseApplication;

$application = new ReleaseApplication();

$application->add((new Command\ComposerUpdate()));

$application->add((new Command\GitHubBranchesCommand()));
$application->add((new Command\GithubReleaseCommand('applications', 'Release applications admin/web/cli')));
$application->add((new Command\GithubReleaseCommand('packages', 'Release packages')));
$application->add((new Command\GithubReleaseCommand('docker', 'Release docker admin/web/cli')));

$application->add((new Command\PackagistInfo()));

$application->run();