services:
    _defaults:
        autowire: true
        autoconfigure: true
#        bind:
#            $appName: '%app.name%'
#            $appVersion: '%app.version%'

    EMS\Release\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Tests/'
            - '../src/Kernel.php'
