services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $githubToken: '%github_token%'
            $githubRepos: '%github_repos%'

    EMS\Release\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Tests/'
            - '../src/Kernel.php'
