version: "3.9"

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
        extra_hosts:
            - "host.docker.internal:host-gateway"

    grafana:
        image: grafana/grafana-oss:latest
        container_name: grafana
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_INSTALL_PLUGINS=
            - GF_UPDATE_CHECKS_ENABLED=false
        ports:
            - "3001:3000"
        depends_on:
            - prometheus
        volumes:
            - grafana-data:/var/lib/grafana
            - ./datasource:/etc/grafana/provisioning:ro
            - ./dashboards:/var/lib/grafana/dashboards:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
            - "traefik.http.routers.grafana.entrypoints=web"
            - "traefik.http.routers.grafana.service=grafana"
            - "traefik.http.services.grafana.loadbalancer.server.port=3000"

volumes:
    grafana-data:

networks:
    default:
        name: skeleton