services:
  setup_elk:
    image: opensearchproject/opensearch:${OS2_STACK_VERSION}
    user: "0"
    command: >
      bash -c '
          echo "All done!";
      '

  es01:
    image: opensearchproject/opensearch:${OS2_STACK_VERSION}
    volumes:
      - os2_data01:/usr/share/opensearch/data
    environment:
      - cluster.name=${CLUSTER_NAME}
      - node.name=es01
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_cluster_manager_nodes=es01
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: ${MEM_LIMIT}

  es02:
    depends_on:
      - es01
    image: opensearchproject/opensearch:${OS2_STACK_VERSION}
    volumes:
      - os2_data02:/usr/share/opensearch/data
    environment:
      - cluster.name=${CLUSTER_NAME}
      - node.name=es02
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: ${MEM_LIMIT}

  es03:
    depends_on:
      - es02
    image: opensearchproject/opensearch:${OS2_STACK_VERSION}
    volumes:
      - os2_data03:/usr/share/opensearch/data
    environment:
      - cluster.name=${CLUSTER_NAME}
      - node.name=es03
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: ${MEM_LIMIT}

  kibana:
    image: opensearchproject/opensearch-dashboards:${OS2_STACK_VERSION}
    environment:
      OPENSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    mem_limit: ${MEM_LIMIT}
