services:
    setup_elk:
        image: opensearchproject/opensearch:${OS2_STACK_VERSION}
        user: "0"
        command: >
            bash -c '
                echo "All done!";
            '

    es01:
        image: opensearchproject/opensearch:${OS2_STACK_VERSION}
        volumes:
            - os2_data1:/usr/share/opensearch/data
        environment:
            - cluster.name=${CLUSTER_NAME}
            - node.name=es01
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
            - "DISABLE_SECURITY_PLUGIN=true"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        mem_limit: ${MEM_LIMIT}

    kibana:
        image: opensearchproject/opensearch-dashboards:${OS2_STACK_VERSION}
        environment:
            OPENSEARCH_HOSTS: '["http://es01:9200"]'
        mem_limit: ${MEM_LIMIT}

    apm-server:
        user: ${DOCKER_USER:-1001}:0
        extends:
            file: docker-elasticms.yml
            service: admin
        command: >
            bash -c '
              echo "APM server is not supported by OpenSearch for the moment";
