services:
    setup_elk:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELK8_STACK_VERSION}
        user: "0"
        command: >
            bash -c '
              echo "Setting file permissions"
              find . -type d -exec chmod 750 {} \;
              find . -type f -exec chmod 640 {} \;

              echo "Waiting for Elasticsearch availability";
              until curl -s http://es01:9200 | grep -q "You Know, for Search"; do sleep 5; done;

              echo "Setting number_of_replicas=0 for all indices (dev single-node)";
              curl -X PUT "http://es01:9200/_all/_settings" \
                   -H "Content-Type: application/json" \
                   -d "{\"index\":{\"number_of_replicas\":0}}"

              echo "Creating dev default template to set number_of_replicas=0 for future indices"
              curl -X PUT "http://es01:9200/_template/dev_template" \
                   -H "Content-Type: application/json" \
                   -d "{\"index_patterns\": [\"*\"], \"settings\": { \"number_of_replicas\": 0 }}"

              echo "All done!";
            '

    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELK8_STACK_VERSION}
        volumes:
            - elk8_data1:/usr/share/elasticsearch/data
        environment:
            - node.name=es01
            - cluster.name=${CLUSTER_NAME}
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - xpack.security.http.ssl.enabled=false
            - xpack.security.transport.ssl.enabled=false
            - xpack.license.self_generated.type=${ELK8_LICENSE}
        mem_limit: ${MEM_LIMIT}
        ulimits:
            memlock:
                soft: -1
                hard: -1
        healthcheck:
            test: [ "CMD-SHELL", "curl -s http://localhost:9200 | grep -q 'You Know, for Search'" ]
            interval: 10s
            timeout: 10s
            retries: 120

    kibana:
        depends_on:
            es01:
                condition: service_healthy
        image: docker.elastic.co/kibana/kibana:${ELK8_STACK_VERSION}
        volumes:
            - kibana:/usr/share/kibana/data
        environment:
            - SERVERNAME=kibana
            - ELASTICSEARCH_HOSTS=http://es01:9200
        mem_limit: ${MEM_LIMIT}
        healthcheck:
            test: [ "CMD-SHELL", "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'" ]
            interval: 10s
            timeout: 10s
            retries: 120

    apm-server:
        image: docker.elastic.co/apm/apm-server:${ELK8_STACK_VERSION}
        depends_on:
            - kibana
        command: >
            apm-server -e
              --strict.perms=false
              -E apm-server.host=0.0.0.0:8200
              -E output.elasticsearch.hosts=["http://es01:9200","http://es02:9200","http://es03:9200"]
              -E apm-server.rum.enabled=true
              -E apm-server.otlp.enabled=true
              -E apm-server.otlp.protocols.http.enabled=true
              -E apm-server.auth.anonymous.enabled=true