services:

  admin:
    image: elasticms/admin:${EMS_VERSION}
    environment:
      - APP_ENV=dev
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - PHP_FPM_MAX_CHILDREN=4
      - PHP_FPM_REQUEST_MAX_MEMORY_IN_MEGABYTES=256
      - CONTAINER_HEAP_PERCENT=0.8
      - MAILER_URL=smtp://mailhog:1025
      - EMSCO_TIKA_SERVER=http://tika:9998
      - EMS_BACKEND_URL=${EMS_BACKEND_URL}
      - INSTANCE_ID=${INSTANCE_ID}
      - 'EMS_ELASTICSEARCH_HOSTS=["http://es01:9200","http://es02:9200","http://es03:9200"]'
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_DRIVER=pgsql
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_SCHEMA=${DB_SCHEMA}
      - S3_ACCESS_KEY_ID=accesskey
      - S3_SECRET_ACCESS_KEY=secretkey
      - S3_DEFAULT_REGION=us-east-1
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR
      - TRUSTED_HOSTS=localhost,*.localhost
    volumes:
      - ./configs/elasticms-admin:/opt/configs
      - ./configs/admin:/opt/src/admin
      - ./configs/document:/opt/src/document

  web:
    image: elasticms/website-skeleton:${EMS_VERSION}
    environment:
      - APP_ENV=dev
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - PHP_FPM_MAX_CHILDREN=8
      - PHP_FPM_REQUEST_MAX_MEMORY_IN_MEGABYTES=64
      - CONTAINER_HEAP_PERCENT=0.8
      - MAILER_URL=smtp://mailhog:1025
      - EMS_BACKEND_URL=${EMS_BACKEND_URL}
      - INSTANCE_ID=${INSTANCE_ID}
      - 'EMS_ELASTICSEARCH_HOSTS=["http://es01:9200","http://es02:9200","http://es03:9200"]'
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - S3_ACCESS_KEY_ID=accesskey
      - S3_SECRET_ACCESS_KEY=secretkey
      - S3_DEFAULT_REGION=us-east-1
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR
      - TRUSTED_HOSTS=localhost,*.localhost
      - EMSCH_ASSET_LOCAL_FOLDER=skeleton
      - VARNISH_ENABLED=true
    volumes:
      - ./configs/elasticms-web:/opt/configs
      - ./dist:/opt/src/public/skeleton:ro
      - ./configs/admin:/opt/src/admin
      - ./configs/document:/opt/src/document
      - ./skeleton:/opt/src/local/${INSTANCE_ID}preview
      - ./skeleton:/opt/src/local/${INSTANCE_ID}live
