# This VirtualHost is autogenerated by the container startup script
<VirtualHost *:9000>
    ServerName {{ .Env.SERVER_NAME }}

{{- if ne .Env.SERVER_ALIASES "" }}
    ServerAlias {{ .Env.SERVER_ALIASES }}
{{- end }}

    LimitRequestLine 16384

    # Uncomment the following line to force Apache to pass the Authorization
    # header to PHP: required for "basic_auth" under PHP-FPM and FastCGI
    #
    # SetEnvIfNoCase ^Authorization$ "(.+)" HTTP_AUTHORIZATION=\$1

    # For Apache 2.4.9 or higher
    # Using SetHandler avoids issues with using ProxyPassMatch in combination
    # with mod_rewrite or mod_autoindex
    <FilesMatch \.php$>
      SetHandler "proxy:unix:/app/var/run/php-fpm/php-fpm.sock|fcgi://localhost/"
    </FilesMatch>

    DocumentRoot {{ .Env.APACHE_PUBLIC_DIR }}
    <Directory {{ .Env.APACHE_PUBLIC_DIR }} >
        AllowOverride None
        Require all granted
        FallbackResource /index.php
    </Directory>

    <DirectoryMatch \/bundles\/[a-f0-9]{40}\/>
      Header set Cache-Control "{{ .Env.APACHE_CACHE_CONTROL }}"
    </DirectoryMatch>

    RewriteEngine On
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    Header setifempty X-Frame-Options "{{ .Env.APACHE_X_FRAME_OPTIONS }}"
    Header setifempty X-XSS-Protection "{{ .Env.APACHE_X_XSS_PROTECTION }}"
    Header setifempty X-Content-Type-Options "{{ .Env.APACHE_X_CONTENT_TYPE_OPTIONS }}"

{{- if ne .Env.APACHE_STRICT_TRANSPORT_SECURITY "" }}
    Header setifempty Strict-Transport-Security "{{ .Env.APACHE_STRICT_TRANSPORT_SECURITY }}"
{{- end }}

{{- if ne .Env.APACHE_CONTENT_SECURITY_POLICY "" }}
    Header setifempty Content-Security-Policy "{{ .Env.APACHE_CONTENT_SECURITY_POLICY }}"
{{- end }}

{{- if ne .Env.APACHE_REFERRER_POLICY "" }}
    Header setifempty Referrer-Policy "{{ .Env.APACHE_REFERRER_POLICY }}"
{{- end }}

{{- if ne .Env.APACHE_PERMISSIONS_POLICY "" }}
    Header setifempty Permissions-Policy "{{ .Env.APACHE_PERMISSIONS_POLICY }}"
{{- end }}

{{- if ne .Env.APACHE_ACCESS_CONTROL_ALLOW_ORIGIN "" }}
    Header set Access-Control-Allow-Origin "{{ .Env.APACHE_ACCESS_CONTROL_ALLOW_ORIGIN }}"
    Header set Access-Control-Allow-Methods "{{ .Env.APACHE_ACCESS_CONTROL_ALLOW_METHODS }}"
    Header set Access-Control-Allow-Headers "{{ .Env.APACHE_ACCESS_CONTROL_ALLOW_HEADERS }}"
{{ end }}

{{- if ne .Env.APACHE_ENVIRONMENTS "" }}

  {{- $environments := env.Getenv "APACHE_ENVIRONMENTS" | jsonArray -}}
  {{- $globalContext := . -}}
  {{- range $env := $environments }}

    Alias {{ $env.alias }}/bundles/emsch_assets {{ $globalContext.Env.APP_SRC_DIR }}/public/bundles/{{ $env.env }}
    Alias {{ $env.alias }} {{ $globalContext.Env.APP_SRC_DIR }}/public

    RewriteCond %{REQUEST_URI} !^{{ $env.alias }}/index.php

    {{- if ne $globalContext.Env.APACHE_CUSTOM_ASSETS_RC "" }}

    RewriteCond %{REQUEST_URI} !^{{ $globalContext.Env.APACHE_CUSTOM_ASSETS_RC }}

    {{ else }}

    RewriteCond %{REQUEST_URI} !^{{ $env.alias }}/bundles

    {{- end }}

    RewriteCond %{REQUEST_URI} !^{{ $env.alias }}/favicon.ico$
    RewriteCond %{REQUEST_URI} !^{{ $env.alias }}/apple-touch-icon.png$
    RewriteCond %{REQUEST_URI} !^{{ $env.alias }}/robots.txt$
    RewriteRule {{ $env.alias }} {{ $env.alias }}/index.php$1 [PT]

  {{- end }}

{{ else }}

  {{- if ne .Env.ALIAS "" }}

    Alias {{ .Env.ALIAS }} {{ .Env.APACHE_PUBLIC_DIR }}
    Alias {{ .Env.ALIAS }}/bundles/emsch_assets {{ .Env.APP_ASSETS_DIR }}/{{ .Env.APACHE_ENVIRONMENT_ALIAS }}

    RewriteCond %{REQUEST_URI} !^{{ .Env.ALIAS }}/index.php
    RewriteCond %{REQUEST_URI} !^{{ .Env.ALIAS }}/bundles
    RewriteCond %{REQUEST_URI} !^{{ .Env.ALIAS }}/favicon.ico$
    RewriteCond %{REQUEST_URI} !^{{ .Env.ALIAS }}/apple-touch-icon.png$
    RewriteCond %{REQUEST_URI} !^{{ .Env.ALIAS }}/robots.txt$
    RewriteRule ^{{ .Env.ALIAS }} {{ .Env.ALIAS }}/index.php$1 [PT]

  {{- end }}

{{- end }}

{{- if ne .Env.APACHE_PROTECTED_URL "" }}
    <Location {{ .Env.APACHE_PROTECTED_URL }} >
      AuthType Basic
      AuthName "Protected Area"
      AuthBasicProvider file
      AuthUserFile {{ .Env.HTPASSWD_FILE }}
      Require valid-user
    </Location>
{{ end }}

    IncludeOptional /opt/etc/apache2/sites-enabled/{{ .Env.ELASTICMS_INSTANCE_NAME }}-app.env

</VirtualHost>